// Code generated by protoc-gen-go-micro. DO NOT EDIT.
// versions:
// - protoc-gen-go-micro v3.10.15
// - protoc              v4.25.3
// source: main.proto

package pb

import (
	context "context"
	client "go.unistack.org/micro/v3/client"
)

var (
	VyborokName = "Vyborok"
)

type VyborokClient interface {
	Health(ctx context.Context, req *HealthReq, opts ...client.CallOption) (*HealthRsp, error)
	Register(ctx context.Context, req *RegisterReq, opts ...client.CallOption) (*RegisterRsp, error)
	Login(ctx context.Context, req *LoginReq, opts ...client.CallOption) (*LoginRsp, error)
	GetMe(ctx context.Context, req *GetMeReq, opts ...client.CallOption) (*ProfileRsp, error)
	Refresh(ctx context.Context, req *RefreshReq, opts ...client.CallOption) (*LoginRsp, error)
	UpdateProfile(ctx context.Context, req *UpdateProfileReq, opts ...client.CallOption) (*ProfileRsp, error)
	GetProfile(ctx context.Context, req *GetProfileReq, opts ...client.CallOption) (*ProfileRsp, error)
	CreatePoll(ctx context.Context, req *CreatePollReq, opts ...client.CallOption) (*PollRsp, error)
	GetPoll(ctx context.Context, req *GetPollReq, opts ...client.CallOption) (*PollRsp, error)
	ListPolls(ctx context.Context, req *ListPollsReq, opts ...client.CallOption) (*ListPollsRsp, error)
	UpdatePoll(ctx context.Context, req *UpdatePollReq, opts ...client.CallOption) (*PollRsp, error)
	DeletePoll(ctx context.Context, req *DeletePollReq, opts ...client.CallOption) (*DeletePollRsp, error)
	ClosePoll(ctx context.Context, req *ClosePollReq, opts ...client.CallOption) (*PollRsp, error)
}

type VyborokServer interface {
	Health(ctx context.Context, req *HealthReq, rsp *HealthRsp) error
	Register(ctx context.Context, req *RegisterReq, rsp *RegisterRsp) error
	Login(ctx context.Context, req *LoginReq, rsp *LoginRsp) error
	GetMe(ctx context.Context, req *GetMeReq, rsp *ProfileRsp) error
	Refresh(ctx context.Context, req *RefreshReq, rsp *LoginRsp) error
	UpdateProfile(ctx context.Context, req *UpdateProfileReq, rsp *ProfileRsp) error
	GetProfile(ctx context.Context, req *GetProfileReq, rsp *ProfileRsp) error
	CreatePoll(ctx context.Context, req *CreatePollReq, rsp *PollRsp) error
	GetPoll(ctx context.Context, req *GetPollReq, rsp *PollRsp) error
	ListPolls(ctx context.Context, req *ListPollsReq, rsp *ListPollsRsp) error
	UpdatePoll(ctx context.Context, req *UpdatePollReq, rsp *PollRsp) error
	DeletePoll(ctx context.Context, req *DeletePollReq, rsp *DeletePollRsp) error
	ClosePoll(ctx context.Context, req *ClosePollReq, rsp *PollRsp) error
}
