// Code generated by protoc-gen-go-micro. DO NOT EDIT.
// protoc-gen-go-micro version: v3.10.15
// source: main.proto

package pb

import (
	context "context"
	v31 "go.unistack.org/micro-client-http/v3"
	v3 "go.unistack.org/micro-server-http/v3"
	client "go.unistack.org/micro/v3/client"
	server "go.unistack.org/micro/v3/server"
	http "net/http"
	time "time"
)

var (
	VyborokServerEndpoints = []v3.EndpointMetadata{
		{
			Name:   "Vyborok.Health",
			Path:   "/health",
			Method: "GET",
			Body:   "",
			Stream: false,
		},
		{
			Name:   "Vyborok.Register",
			Path:   "/auth/register",
			Method: "POST",
			Body:   "*",
			Stream: false,
		},
		{
			Name:   "Vyborok.Login",
			Path:   "/auth/login",
			Method: "POST",
			Body:   "*",
			Stream: false,
		},
		{
			Name:   "Vyborok.GetMe",
			Path:   "/auth/me",
			Method: "GET",
			Body:   "",
			Stream: false,
		},
		{
			Name:   "Vyborok.Refresh",
			Path:   "/auth/refresh",
			Method: "POST",
			Body:   "*",
			Stream: false,
		},
		{
			Name:   "Vyborok.UpdateProfile",
			Path:   "/user/profile",
			Method: "PUT",
			Body:   "*",
			Stream: false,
		},
		{
			Name:   "Vyborok.GetProfile",
			Path:   "/user/{username}",
			Method: "GET",
			Body:   "",
			Stream: false,
		},
	}
)

type vyborokClient struct {
	c    client.Client
	name string
}

func NewVyborokClient(name string, c client.Client) VyborokClient {
	return &vyborokClient{c: c, name: name}
}

func (c *vyborokClient) Health(ctx context.Context, req *HealthReq, opts ...client.CallOption) (*HealthRsp, error) {
	errmap := make(map[string]interface{}, 1)
	errmap["default"] = &ErrorRsp{}
	opts = append(opts,
		v31.ErrorMap(errmap),
	)
	opts = append(opts,
		v31.Method(http.MethodGet),
		v31.Path("/health"),
	)
	td := time.Duration(1000000000)
	opts = append(opts, client.WithRequestTimeout(td))
	rsp := &HealthRsp{}
	err := c.c.Call(ctx, c.c.NewRequest(c.name, "Vyborok.Health", req), rsp, opts...)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *vyborokClient) Register(ctx context.Context, req *RegisterReq, opts ...client.CallOption) (*RegisterRsp, error) {
	errmap := make(map[string]interface{}, 1)
	errmap["default"] = &ErrorRsp{}
	opts = append(opts,
		v31.ErrorMap(errmap),
	)
	opts = append(opts,
		v31.Method(http.MethodPost),
		v31.Path("/auth/register"),
		v31.Body("*"),
	)
	td := time.Duration(1000000000)
	opts = append(opts, client.WithRequestTimeout(td))
	rsp := &RegisterRsp{}
	err := c.c.Call(ctx, c.c.NewRequest(c.name, "Vyborok.Register", req), rsp, opts...)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *vyborokClient) Login(ctx context.Context, req *LoginReq, opts ...client.CallOption) (*LoginRsp, error) {
	errmap := make(map[string]interface{}, 1)
	errmap["default"] = &ErrorRsp{}
	opts = append(opts,
		v31.ErrorMap(errmap),
	)
	opts = append(opts,
		v31.Method(http.MethodPost),
		v31.Path("/auth/login"),
		v31.Body("*"),
	)
	td := time.Duration(1000000000)
	opts = append(opts, client.WithRequestTimeout(td))
	rsp := &LoginRsp{}
	err := c.c.Call(ctx, c.c.NewRequest(c.name, "Vyborok.Login", req), rsp, opts...)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *vyborokClient) GetMe(ctx context.Context, req *GetMeReq, opts ...client.CallOption) (*ProfileRsp, error) {
	errmap := make(map[string]interface{}, 1)
	errmap["default"] = &ErrorRsp{}
	opts = append(opts,
		v31.ErrorMap(errmap),
	)
	opts = append(opts,
		v31.Method(http.MethodGet),
		v31.Path("/auth/me"),
	)
	td := time.Duration(1000000000)
	opts = append(opts, client.WithRequestTimeout(td))
	rsp := &ProfileRsp{}
	err := c.c.Call(ctx, c.c.NewRequest(c.name, "Vyborok.GetMe", req), rsp, opts...)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *vyborokClient) Refresh(ctx context.Context, req *RefreshReq, opts ...client.CallOption) (*LoginRsp, error) {
	errmap := make(map[string]interface{}, 1)
	errmap["default"] = &ErrorRsp{}
	opts = append(opts,
		v31.ErrorMap(errmap),
	)
	opts = append(opts,
		v31.Method(http.MethodPost),
		v31.Path("/auth/refresh"),
		v31.Body("*"),
	)
	td := time.Duration(1000000000)
	opts = append(opts, client.WithRequestTimeout(td))
	rsp := &LoginRsp{}
	err := c.c.Call(ctx, c.c.NewRequest(c.name, "Vyborok.Refresh", req), rsp, opts...)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *vyborokClient) UpdateProfile(ctx context.Context, req *UpdateProfileReq, opts ...client.CallOption) (*ProfileRsp, error) {
	errmap := make(map[string]interface{}, 1)
	errmap["default"] = &ErrorRsp{}
	opts = append(opts,
		v31.ErrorMap(errmap),
	)
	opts = append(opts,
		v31.Method(http.MethodPut),
		v31.Path("/user/profile"),
		v31.Body("*"),
	)
	td := time.Duration(1000000000)
	opts = append(opts, client.WithRequestTimeout(td))
	rsp := &ProfileRsp{}
	err := c.c.Call(ctx, c.c.NewRequest(c.name, "Vyborok.UpdateProfile", req), rsp, opts...)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *vyborokClient) GetProfile(ctx context.Context, req *GetProfileReq, opts ...client.CallOption) (*ProfileRsp, error) {
	errmap := make(map[string]interface{}, 1)
	errmap["default"] = &ErrorRsp{}
	opts = append(opts,
		v31.ErrorMap(errmap),
	)
	opts = append(opts,
		v31.Method(http.MethodGet),
		v31.Path("/user/{username}"),
	)
	td := time.Duration(1000000000)
	opts = append(opts, client.WithRequestTimeout(td))
	rsp := &ProfileRsp{}
	err := c.c.Call(ctx, c.c.NewRequest(c.name, "Vyborok.GetProfile", req), rsp, opts...)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

type vyborokServer struct {
	VyborokServer
}

func (h *vyborokServer) Health(ctx context.Context, req *HealthReq, rsp *HealthRsp) error {
	var cancel context.CancelFunc
	td := time.Duration(1000000000)
	ctx, cancel = context.WithTimeout(ctx, td)
	defer cancel()
	return h.VyborokServer.Health(ctx, req, rsp)
}

func (h *vyborokServer) Register(ctx context.Context, req *RegisterReq, rsp *RegisterRsp) error {
	var cancel context.CancelFunc
	td := time.Duration(1000000000)
	ctx, cancel = context.WithTimeout(ctx, td)
	defer cancel()
	return h.VyborokServer.Register(ctx, req, rsp)
}

func (h *vyborokServer) Login(ctx context.Context, req *LoginReq, rsp *LoginRsp) error {
	var cancel context.CancelFunc
	td := time.Duration(1000000000)
	ctx, cancel = context.WithTimeout(ctx, td)
	defer cancel()
	return h.VyborokServer.Login(ctx, req, rsp)
}

func (h *vyborokServer) GetMe(ctx context.Context, req *GetMeReq, rsp *ProfileRsp) error {
	var cancel context.CancelFunc
	td := time.Duration(1000000000)
	ctx, cancel = context.WithTimeout(ctx, td)
	defer cancel()
	return h.VyborokServer.GetMe(ctx, req, rsp)
}

func (h *vyborokServer) Refresh(ctx context.Context, req *RefreshReq, rsp *LoginRsp) error {
	var cancel context.CancelFunc
	td := time.Duration(1000000000)
	ctx, cancel = context.WithTimeout(ctx, td)
	defer cancel()
	return h.VyborokServer.Refresh(ctx, req, rsp)
}

func (h *vyborokServer) UpdateProfile(ctx context.Context, req *UpdateProfileReq, rsp *ProfileRsp) error {
	var cancel context.CancelFunc
	td := time.Duration(1000000000)
	ctx, cancel = context.WithTimeout(ctx, td)
	defer cancel()
	return h.VyborokServer.UpdateProfile(ctx, req, rsp)
}

func (h *vyborokServer) GetProfile(ctx context.Context, req *GetProfileReq, rsp *ProfileRsp) error {
	var cancel context.CancelFunc
	td := time.Duration(1000000000)
	ctx, cancel = context.WithTimeout(ctx, td)
	defer cancel()
	return h.VyborokServer.GetProfile(ctx, req, rsp)
}

func RegisterVyborokServer(s server.Server, sh VyborokServer, opts ...server.HandlerOption) error {
	type vyborok interface {
		Health(ctx context.Context, req *HealthReq, rsp *HealthRsp) error
		Register(ctx context.Context, req *RegisterReq, rsp *RegisterRsp) error
		Login(ctx context.Context, req *LoginReq, rsp *LoginRsp) error
		GetMe(ctx context.Context, req *GetMeReq, rsp *ProfileRsp) error
		Refresh(ctx context.Context, req *RefreshReq, rsp *LoginRsp) error
		UpdateProfile(ctx context.Context, req *UpdateProfileReq, rsp *ProfileRsp) error
		GetProfile(ctx context.Context, req *GetProfileReq, rsp *ProfileRsp) error
	}
	type Vyborok struct {
		vyborok
	}
	h := &vyborokServer{sh}
	opts = append(opts, v3.HandlerEndpoints(VyborokServerEndpoints))
	return s.Handle(s.NewHandler(&Vyborok{h}, opts...))
}
